name: Release iOS
description: Release iOS App

inputs:
    version-number:
        description: "The current version number"
        required: true
    build-number:
        description: "The current build number"
        required: true

runs:
    using: composite
    steps:
        - name: Set up Node
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ env.PRIVATE_NPM_REPOSITORY_URL }}

        - name: Set up iOS
          uses: ./.github/actions/setup-ios

        - name: Update Configuration
          uses: ./.github/actions/update-config
          with:
              host-name: ${{ env.HOST_NAME }}

        - name: Publish iOS App
          if: ${{ env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'SNAPSHOT' }}
          shell: bash
          working-directory: ios
          run: bundle exec fastlane ${{ env.BUILD_TYPE == 'RELEASE' && 'main' || 'develop' }} version:"${{ inputs.version-number }}" build_number:"${{ inputs.build-number }}"
