name: Setup Node
description: Setup Node.js and install dependencies

inputs:
    registry-url:
        description: "The url to publish the package to. If no publication is necessary, the parameter is not provided."
        required: false
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: false
        default: "false"

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4

        - name: Configure Yarn for private registry
          if: inputs.registry-url != ''
          shell: bash
          run: |
              yarn config set npmScopes.nevis-security.npmRegistryServer ${{ inputs.registry-url }}
              yarn config set npmScopes.nevis-security.npmAlwaysAuth true
              yarn config set npmScopes.nevis-security.npmAuthToken ${{ env.NODE_AUTH_TOKEN }}

        - name: Install dependencies
          shell: bash
          run: yarn install
