name: Setup Node
description: Setup Node.js and install dependencies

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: false
        default: "false"

outputs:
    cache-hit:
        description: "True in case the node cache was hit, false otherwise."
        value: ${{ steps.yarn-cache.outputs.cache-hit }}

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4

        - name: Cache dependencies
          id: yarn-cache
          uses: actions/cache@v4
          with:
              path: node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}-${{ inputs.new-arch-enabled == 'true' && 'new-arch' || 'old-arch' }}

        - name: Install dependencies
          if: steps.yarn-cache.outputs.cache-hit != 'true'
          shell: bash
          run: yarn install --frozen-lockfile
