name: Build iOS
description: Build iOS App

runs:
    using: composite
    steps:
        - name: Set up Node
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ env.PRIVATE_NPM_REPOSITORY_URL }}

        - name: Set up iOS
          uses: ./.github/actions/setup-ios

        - name: Build iOS App
          uses: maierj/fastlane-action@v3.1.0
          with:
            lane: 'pr'
            subdirectory: 'ios'
