name: Build iOS
description: Build iOS App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Set up Node
          uses: ./.github/actions/setup-node
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Set up iOS
          uses: ./.github/actions/setup-ios
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Build iOS App
          shell: bash
          run: yarn react-native build-ios --mode Debug --verbose
