name: Build iOS
description: Build iOS example app
    Required environment variables
    * XCODE_VERSION

inputs:
    build-4-new-arch:
        description: "If true, the artifact will be built for the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Set Xcode version
          uses: maxim-lobanov/setup-xcode@v1
          with:
              xcode-version: ${{ env.XCODE_VERSION }}

        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup
          with:
              build-4-new-arch: ${{ inputs.build-4-new-arch }}

        - name: Cache cocoapods
          if: steps.setup-node.outputs.cache-hit == 'true'
          id: cocoapods-cache
          uses: actions/cache@v3
          with:
              path: |
                  **/ios/Pods
                  **/ios/build/generated
              key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}-${{ inputs.build-4-new-arch == 'true' && 'new-arch' || 'old-arch' }}-${{ env.BUILD_TYPE }}

        - name: Install cocoapods - new architecture
          shell: bash
          if: steps.cocoapods-cache.outputs.cache-hit != 'true' && inputs.build-4-new-arch == 'true'
          run: yarn pods:new

        - name: Install cocoapods - old architecture
          shell: bash
          if: steps.cocoapods-cache.outputs.cache-hit != 'true' && inputs.build-4-new-arch == 'false'
          run: yarn pods:old

        - name: Build example for iOS
          shell: bash
          run: yarn ios:build

        - name: Slack report
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: ./.github/actions/slack-report
          with:
              platform: 'iOS'
              is-workflow-state-success: success()
