name: Build iOS
description: Build iOS App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true
    version-number:
        description: "The current version number"
        required: false
    build-number:
        description: "The current build number"
        required: false

runs:
    using: composite
    steps:
        - name: Set Xcode version
          uses: maxim-lobanov/setup-xcode@v1
          with:
              xcode-version: ${{ env.XCODE_VERSION }}

        - name: Set up Node
          id: setup-node
          uses: ./.github/actions/setup
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Cache Cocoapods
          if: steps.setup-node.outputs.cache-hit == 'true'
          id: cocoapods-cache
          uses: actions/cache@v3
          with:
              path: |
                  **/ios/Pods
                  **/ios/build/generated
              key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}-${{ inputs.new-arch-enabled == 'true' && 'new-arch' || 'old-arch' }}-${{ env.BUILD_TYPE }}

        - name: Install Cocoapods - new architecture
          if: steps.cocoapods-cache.outputs.cache-hit != 'true' && inputs.new-arch-enabled == 'true'
          shell: bash
          run: yarn pods:new

        - name: Install Cocoapods - old architecture
          if: steps.cocoapods-cache.outputs.cache-hit != 'true' && inputs.new-arch-enabled == 'false'
          shell: bash
          run: yarn pods:old

        - name: Build iOS App
          if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
          shell: bash
          run: yarn react-native build-ios --mode Debug

        - name: Update Configuration
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          uses: ./.github/actions/update-config
          with:
              host-name: ${{ env.HOST_NAME }}

        - name: Cache RubyGem Dependencies
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: ${{ env.RUBY_VERSION }}
              bundler-cache: true
              working-directory: 'ios'

        - name: Publish iOS App
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          env:
              MATCH_GIT_AUTHORIZATION: ${{ env.MATCH_GIT_AUTHORIZATION }}
              MATCH_GIT_URL: ${{ env.MATCH_GIT_URL }}
              MATCH_PASSWORD: ${{ env.MATCH_PASSWORD }}
              DEVELOPER_PORTAL_TEAM_ID: ${{ env.DEVELOPER_PORTAL_TEAM_ID }}
              CODE_SIGNING_IDENTITY: ${{ env.CODE_SIGNING_IDENTITY }}
              PROVISIONING_PROFILE_SPECIFIER: ${{ env.PROVISIONING_PROFILE_SPECIFIER }}
              FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
              FIREBASE_APP_ID_IOS: ${{ env.FIREBASE_APP_ID_IOS }}
              TEMP_KEYCHAIN_NAME: ${{ env.TEMP_KEYCHAIN_NAME }}
              SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          uses: maierj/fastlane-action@v3.0.0
          with:
              lane: 'main'
              subdirectory: 'ios'
              options: '{ "version": "${{ inputs.version-number }}",
                          "build_number": "${{ inputs.build-number }}"
                        }'
