name: Update Configuration
description: 'Updates the configuration files'

inputs:
    host-name:
        description: 'The host name to update'
        required: true

runs:
    using: composite
    steps:
        - name: Update Configuration (hostname)
          uses: jossef/action-set-json-field@v2.2
          with:
              file: assets/config_authentication_cloud.json
              field: sdk.hostname
              value: '${{ inputs.host-name }}.mauth.nevis.cloud'
