name: Update Configuration
description: 'Updates the configuration files'

inputs:
    host-name:
        description: 'The host name to update'
        required: true

runs:
    using: composite
    steps:
        - name: Update Configuration (hostname)
          shell: bash
          run: |
            file="assets/config_authentication_cloud.json"
            tmp_file="$(mktemp)"
            jq --arg hostname "${{ inputs.host-name }}.mauth.nevis.cloud" '.sdk.hostname = $hostname' "$file" > "$tmp_file" && mv "$tmp_file" "$file"
