name: Update Configuration
description: 'Updates the configuration files'

inputs:
    host-name:
        description: 'The host name to update'
        required: true

runs:
    using: composite
    steps:
        - name: Update Configuration (hostname)
          shell: bash
          run: |
            file="assets/config_authentication_cloud.json"
            jq '.sdk.hostname = "${{ inputs.host-name }}.mauth.nevis.cloud"' "$file" > /tmp/jq_out.json && mv /tmp/jq_out.json "$file"
