source "https://cdn.cocoapods.org"

def node_require(script)
	# Resolve script with node to allow for hoisting
	require Pod::Executable.execute_command("node", ["-p", "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require("react-native/scripts/react_native_pods.rb")
node_require("react-native-permissions/scripts/setup.rb")

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
	"Camera",
	"FaceID"
])

linkage = ENV["USE_FRAMEWORKS"]
unless linkage.nil?
	Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
	use_frameworks! linkage: linkage.to_sym
end

target "nevis_mobile_authentication_sdk_example_app_react" do
	pod "NevisMobileAuthentication-Debug", "~> 4.3.0", configurations: ["Debug"]
	pod "NevisMobileAuthentication", "~> 4.3.0", configurations: ["Release"]

	config = use_native_modules!

	use_react_native!(
		path: config[:reactNativePath],
		# An absolute path to your application root.
		app_path: "#{Pod::Config.instance.installation_root}/.."
	)

	target "nevis_mobile_authentication_sdk_example_app_reactTests" do
		inherit! :complete
		# Pods for testing
	end

	post_install do |installer|
		installer.pods_project.targets.select.each do |target|
			target.build_configurations.each do |c|
				c.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = min_ios_version_supported
			end
		end

		# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
		react_native_post_install(
			installer,
			config[:reactNativePath],
			mac_catalyst_enabled: false,
			# ccache_enabled: true
		)
	end
end
