name: Setup Android
description: Setup Android resources and install dependencies

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Install JDK
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu'
              java-version: ${{ env.JAVA_VERSION }}

        - name: Cache RubyGem Dependencies
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: ${{ env.RUBY_VERSION }}
              bundler-cache: true
              working-directory: 'android'

        - name: Decode Keystore
          uses: timheuer/base64-to-file@v1
          with:
              fileName: 'keystore-example-app.jks'
              fileDir: './android/etc'
              encodedString: ${{ env.KEYSTORE_FILE }}

        - name: Cache Gradle
          uses: actions/cache@v4
          with:
              path: |
                  ~/.gradle/wrapper
                  ~/.gradle/caches
              key: ${{ runner.os }}-gradle-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties') }}-${{ inputs.new-arch-enabled == 'true' && 'new-arch' || 'old-arch' }}-${{ env.BUILD_TYPE }}
