name: Setup iOS
description: Setup iOS resources and install dependencies

runs:
    using: composite
    steps:
        - name: Set Xcode version
          uses: maxim-lobanov/setup-xcode@v1
          with:
              xcode-version: ${{ env.XCODE_VERSION }}

        - name: Cache RubyGem Dependencies
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: ${{ env.RUBY_VERSION }}
              bundler-cache: true
              working-directory: 'ios'

        - name: Add Private Cocoapods Repo
          if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
          shell: bash
          working-directory: 'ios'
          run: |
              bundle exec pod repo remove ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_NAME }} &> /dev/null || true
              bundle exec pod repo add ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_NAME }} ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_URL }}
