name: Setup iOS
description: Setup iOS resources and install dependencies

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Set Xcode version
          uses: maxim-lobanov/setup-xcode@v1
          with:
              xcode-version: ${{ env.XCODE_VERSION }}

        - name: Cache RubyGem Dependencies
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: ${{ env.RUBY_VERSION }}
              bundler-cache: true
              working-directory: 'ios'

        - name: Add Private Cocoapods Repo
          if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
          shell: bash
          run: |
              pod repo remove ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_NAME }} &> /dev/null || true
              pod repo add ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_NAME }} ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY_URL }}

        - name: Install Cocoapods - new architecture
          if: inputs.new-arch-enabled == 'true'
          shell: bash
          run: yarn pods:new

        - name: Install Cocoapods - old architecture
          if: inputs.new-arch-enabled == 'false'
          shell: bash
          run: yarn pods:old
