name: Build Android
description: Build Android App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup-node
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Set up Android
          uses: ./.github/actions/setup-android
          with:
              cache-gradle: ${{ steps.setup-node.outputs.cache-hit == 'true' }}

        - name: Build Android App
          env:
              PRIVATE_NATIVE_REPOSITORY_URL: ${{ env.PRIVATE_NATIVE_ANDROID_REPOSITORY_URL }}
          uses: maierj/fastlane-action@v3.1.0
          with:
              lane: 'pr'
              subdirectory: 'android'
