name: Build Android
description: Build Android App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup-node
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Set up Android
          uses: ./.github/actions/setup-android
          with:
              cache-gradle: ${{ steps.setup-node.outputs.cache-hit == 'true' }}

        - name: Build Android App
          shell: bash
          run: |
              if [[ ${{ inputs.new-arch-enabled }} == 'true' ]]; then
                  NEW_ARCH_ENABLED=true
              else
                  NEW_ARCH_ENABLED=false
              fi

              yarn react-native build-android --mode Debug --extra-params -PnewArchEnabled=$NEW_ARCH_ENABLED
