name: Build Android
description: Build Android App

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ env.PRIVATE_NPM_REPOSITORY_URL }}

        - name: Set up Android
          uses: ./.github/actions/setup-android

        - name: Build Android App
          shell: bash
          working-directory: android
          env:
              PRIVATE_NATIVE_REPOSITORY_URL: ${{ env.PRIVATE_NATIVE_ANDROID_REPOSITORY_URL }}
          run: bundle exec fastlane pr
