name: Build Android
description: Build Android App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ env.PRIVATE_NPM_REPOSITORY_URL }}
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Set up Android
          uses: ./.github/actions/setup-android
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Build Android App
          env:
              PRIVATE_NATIVE_REPOSITORY_URL: ${{ env.PRIVATE_NATIVE_ANDROID_REPOSITORY_URL }}
          uses: maierj/fastlane-action@v3.1.0
          with:
              lane: 'pr'
              subdirectory: 'android'
              options: |
                  {
                    "new_arch_enabled": "${{ inputs.new-arch-enabled }}"
                  }
