name: Build Android
description: Build Android App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true
    version-number:
        description: "The current version number"
        required: false
    build-number:
        description: "The current build number"
        required: false

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Install JDK
          uses: actions/setup-java@v3
          with:
              distribution: 'zulu'
              java-version: ${{ env.JAVA_VERSION }}

        - name: Finalize Android SDK
          shell: bash
          run: /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

        - name: Cache Gradle
          if: steps.setup-node.outputs.cache-hit == 'true'
          uses: actions/cache@v3
          with:
              path: |
                  ~/.gradle/wrapper
                  ~/.gradle/caches
              key: ${{ runner.os }}-gradle-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties') }}-${{ inputs.new-arch-enabled == 'true' && 'new-arch' || 'old-arch' }}-${{ env.BUILD_TYPE }}

        - name: Build Android App
          if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
          shell: bash
          run: |
              if [[ ${{ inputs.new-arch-enabled }} == 'true' ]]; then
                  NEW_ARCH_ENABLED=true
              else
                  NEW_ARCH_ENABLED=false
              fi

              yarn react-native build-android --mode Debug --extra-params -PnewArchEnabled=$NEW_ARCH_ENABLED

        - name: Update Configuration
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          uses: ./.github/actions/update-config
          with:
              host-name: ${{ env.HOST_NAME }}

        - name: Cache RubyGem Dependencies
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          uses: ruby/setup-ruby@v1
          with:
              ruby-version: ${{ env.RUBY_VERSION }}
              bundler-cache: true
              working-directory: 'android'

        - name: Decode Keystore
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          uses: timheuer/base64-to-file@v1
          with:
              fileName: 'keystore-example-app.jks'
              fileDir: './android/etc'
              encodedString: ${{ env.KEYSTORE_FILE }}

        - name: Publish Android App
          if: ${{ env.BUILD_TYPE == 'RELEASE' }}
          env:
              GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
              SIGNING_CONFIGS: ${{ env.SIGNING_CONFIGS }}
              GITHUB_USERNAME: ${{ env.GITHUB_USERNAME }}
              GITHUB_PERSONAL_ACCESS_TOKEN: ${{ env.GITHUB_PERSONAL_ACCESS_TOKEN }}
              FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
              FIREBASE_APP_ID_ANDROID: ${{ env.FIREBASE_APP_ID_ANDROID }}
              SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          uses: maierj/fastlane-action@v3.0.0
          with:
              lane: 'main'
              subdirectory: 'android'
              options: '{ "version": "${{ inputs.version-number }}",
                          "build_number": "${{ inputs.build-number }}",
                          "new_arch_enabled": "${{ inputs.new-arch-enabled }}"
                        }'
