name: Release Android
description: Release Android App

inputs:
    new-arch-enabled:
        description: "Flag that tells whether enable support to the new architecture."
        required: true
    version-number:
        description: "The current version number"
        required: true
    build-number:
        description: "The current build number"
        required: true

runs:
    using: composite
    steps:
        - name: Setup
          id: setup-node
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ env.PRIVATE_NPM_REPOSITORY_URL }}
              new-arch-enabled: ${{ inputs.new-arch-enabled }}

        - name: Set up Android
          uses: ./.github/actions/setup-android
          with:
              new-arch-enabled: ${{ inputs.new-arch-enabled }}


        - name: Update Configuration
          uses: ./.github/actions/update-config
          with:
              host-name: ${{ env.HOST_NAME }}

        - name: Bundle Android Assets
          shell: bash
          run: yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

        - name: Publish Android App
          if: ${{ env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'SNAPSHOT' }}
          env:
              GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
              SIGNING_CONFIGS: ${{ env.SIGNING_CONFIGS }}
              GH_USERNAME: ${{ env.GH_USERNAME }}
              GH_PERSONAL_ACCESS_TOKEN: ${{ env.GH_PERSONAL_ACCESS_TOKEN }}
              FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
              FIREBASE_APP_ID_ANDROID: ${{ env.FIREBASE_APP_ID_ANDROID }}
              SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
              PRIVATE_NATIVE_REPOSITORY_URL: ${{ env.PRIVATE_NATIVE_ANDROID_REPOSITORY_URL }}
          uses: maierj/fastlane-action@v3.1.0
          with:
              lane: ${{ env.BUILD_TYPE == 'RELEASE' && 'main' || 'develop' }}
              subdirectory: 'android'
              options: |
                {
                  "version": "${{ inputs.version-number }}",
                  "build_number": "${{ inputs.build-number }}",
                  "new_arch_enabled": "${{ inputs.new-arch-enabled }}"
                }
