name: Develop Branch Commit

on:
    push:
        branches: ['develop']
    workflow_dispatch:
        inputs:
            ios-runner-type:
                type: choice
                required: true
                description: "Runner type"
                default: "self-hosted"
                options:
                    - "self-hosted"
                    - "macos-15"

env:
    BUILD_TYPE: 'SNAPSHOT' #BUILD_TYPE: Type of the build; allowed values: 'SNAPSHOT', 'RELEASE'
    GH_USERNAME: ${{ vars.GH_USERNAME }}
    GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    XCODE_VERSION: 16.2
    JAVA_VERSION: 17
    RUBY_VERSION: 3.4.2

jobs:
    lint-and-format:
        name: Lint & Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node
              uses: ./.github/actions/setup-node

            - name: Lint Files
              run: yarn lint

            - name: Run Formatter
              run: yarn formatcheck

            - name: Run Ruby linter for Android
              uses: ./.github/actions/run-ruby-linter
              with:
                  working-directory: 'android'

            - name: Run Ruby linter for iOS
              uses: ./.github/actions/run-ruby-linter
              with:
                  working-directory: 'ios'
